### ISSUE TITLE
🕵️ use alpha-3 to represent country

### ISSUE THREAD

**Issue by junbohuang** [semantic-systems/coypu-feeds#1]
https://www.iban.com/country-codes
This will simplify the use of this API in the context of Coypu, since alpha-3 is used everywhere in Coypu.

But I am not sure about the list of countries supported by RSS and GDELT.

**Comment by as311-ops** [comment]
Yes, alpha-3 would be very useful as a filter criteria!

**Comment by as311-ops** [comment]
Are there categories in GDELT? e.g. everything about violent protests or natural disasters? Sometimes I do not have the necessary keywords, so categories would be more convenient for the API.

**Comment by junbohuang** [comment]
> Also: How do I use multiple keywords?

separate them with ;
@rudygarrido can you add this in the README?

**Comment by junbohuang** [comment]
alpha-3 integration is WIP

**Comment by rudygarrido** [comment]
The separation with semicolons is already in the README. I'll try to make it easier to spot or in a clearer way.

**Comment by rudygarrido** [comment]
Semicolon separation has been made clearer in the README ✅  Should be visible once the main branch gets merged.

**Comment by rudygarrido** [comment]
Alpha-3 implemented ✅ README has been updated with the main branch merge
