### ISSUE TITLE
normalize timestamps

### ISSUE THREAD

**Issue by as311-ops** [semantic-systems/coypu-feeds#5]
Now: 

Tue, 04 Apr 2023 03:15:00
Mon, 03 Apr 2023 22:11:18 +0530

If possible, please normalize to CoyPu date format

**Comment by junbohuang** [comment]
@as311-ops can you provide an example? or a link to the coypu date format?

**Comment by rudygarrido** [comment]
Timestamps normalized, and the date format changed to xsd:DateTime. Do let us know if that is not the desired format.
